/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdminData = IDL.Record({ 'id' : IDL.Text, 'password' : IDL.Text });
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'author' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'blobHash' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'blobHash' : IDL.Text,
  'createdAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'addTestimonial' : IDL.Func(
      [AdminData, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'addVideo' : IDL.Func(
      [AdminData, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addVideoByUrl' : IDL.Func(
      [AdminData, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteTestimonial' : IDL.Func([AdminData, IDL.Text], [], []),
  'deleteVideo' : IDL.Func([AdminData, IDL.Text], [], []),
  'getHeroImageHash' : IDL.Func([], [IDL.Text], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'setHeroImageHash' : IDL.Func([AdminData, IDL.Text], [], []),
  'addGalleryImage' : IDL.Func([AdminData, IDL.Text, IDL.Text], [IDL.Text], []),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'deleteGalleryImage' : IDL.Func([AdminData, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdminData = IDL.Record({ 'id' : IDL.Text, 'password' : IDL.Text });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'author' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'blobHash' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'blobHash' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  
  return IDL.Service({
    'addTestimonial' : IDL.Func(
        [AdminData, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'addVideo' : IDL.Func(
        [AdminData, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addVideoByUrl' : IDL.Func(
        [AdminData, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteTestimonial' : IDL.Func([AdminData, IDL.Text], [], []),
    'deleteVideo' : IDL.Func([AdminData, IDL.Text], [], []),
    'getHeroImageHash' : IDL.Func([], [IDL.Text], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'setHeroImageHash' : IDL.Func([AdminData, IDL.Text], [], []),
    'addGalleryImage' : IDL.Func([AdminData, IDL.Text, IDL.Text], [IDL.Text], []),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'deleteGalleryImage' : IDL.Func([AdminData, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
