/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminData { 'id' : string, 'password' : string }
export interface Testimonial {
  'id' : string,
  'content' : string,
  'createdAt' : bigint,
  'role' : string,
  'author' : string,
  'rating' : bigint,
}
export interface Video {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'blobHash' : string,
  'videoUrl' : string,
}
export interface GalleryImage {
  'id' : string,
  'title' : string,
  'blobHash' : string,
  'createdAt' : bigint,
}
export interface _SERVICE {
  'addTestimonial' : ActorMethod<
    [AdminData, string, string, string, bigint],
    string
  >,
  'addVideo' : ActorMethod<[AdminData, string, string, string], string>,
  'addVideoByUrl' : ActorMethod<[AdminData, string, string, string], string>,
  'deleteTestimonial' : ActorMethod<[AdminData, string], undefined>,
  'deleteVideo' : ActorMethod<[AdminData, string], undefined>,
  'getHeroImageHash' : ActorMethod<[], string>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getVideos' : ActorMethod<[], Array<Video>>,
  'setHeroImageHash' : ActorMethod<[AdminData, string], undefined>,
  'addGalleryImage' : ActorMethod<[AdminData, string, string], string>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'deleteGalleryImage' : ActorMethod<[AdminData, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
